name: 'gtm_case_josh'
version: '1.0.0'
config-version: 2

profile: 'gtm_case_josh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gtm_case_josh:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
